
class Menu {
    static void menu(){
        Scanner scanner = new Scanner(System.in);
        byte opcion;
        System.out.println("===VETERINARIA PATITAS==");
        System.out.println("\nBienvenido, estamos para servirle.\n");
        System.out.println("1. Insertar mascota\n2. Actualizar mascota\n3. Eliminar mascota\n4. Buscar mascota por nombre\n5. Listar todas las mascotas");
        System.out.println("Seleccione una opcion: ");
        opcion = scanner.nextByte();
        

    }
}